/**
 * Country names for GDELT's country codes.
 *
 * GDELT geocodes with FIPS 10-4 codes, NOT ISO 3166 — and the two disagree
 * in exactly the places that matter here: "CH" is China (not Switzerland,
 * which is "SZ"), "GM" is Germany, "UK" is the United Kingdom, "AS" is
 * Australia and "AU" Austria, "IZ" is Iraq, "JA" Japan, "KS" South Korea.
 * Reading these as ISO codes would put a surge in Chinese reporting on
 * Switzerland.
 *
 * A code not in this table is shown as the code itself rather than guessed.
 * Pure data; safe anywhere.
 */

export const FIPS_COUNTRY_NAMES: Record<string, string> = {
  AE: 'United Arab Emirates',
  AF: 'Afghanistan',
  AG: 'Algeria',
  AJ: 'Azerbaijan',
  AL: 'Albania',
  AM: 'Armenia',
  AO: 'Angola',
  AR: 'Argentina',
  AS: 'Australia',
  AU: 'Austria',
  BA: 'Bahrain',
  BB: 'Barbados',
  BC: 'Botswana',
  BE: 'Belgium',
  BF: 'Bahamas',
  BG: 'Bangladesh',
  BH: 'Belize',
  BK: 'Bosnia and Herzegovina',
  BL: 'Bolivia',
  BM: 'Myanmar',
  BN: 'Benin',
  BO: 'Belarus',
  BR: 'Brazil',
  BU: 'Bulgaria',
  BX: 'Brunei',
  BY: 'Burundi',
  CA: 'Canada',
  CB: 'Cambodia',
  CD: 'Chad',
  CE: 'Sri Lanka',
  CF: 'Republic of the Congo',
  CG: 'Democratic Republic of the Congo',
  CH: 'China',
  CI: 'Chile',
  CM: 'Cameroon',
  CO: 'Colombia',
  CS: 'Costa Rica',
  CU: 'Cuba',
  CV: 'Cape Verde',
  CY: 'Cyprus',
  DA: 'Denmark',
  DJ: 'Djibouti',
  DR: 'Dominican Republic',
  EC: 'Ecuador',
  EG: 'Egypt',
  EI: 'Ireland',
  EK: 'Equatorial Guinea',
  EN: 'Estonia',
  ER: 'Eritrea',
  ES: 'El Salvador',
  ET: 'Ethiopia',
  EZ: 'Czechia',
  FI: 'Finland',
  FJ: 'Fiji',
  FR: 'France',
  GA: 'Gambia',
  GB: 'Gabon',
  GG: 'Georgia',
  GH: 'Ghana',
  GM: 'Germany',
  GR: 'Greece',
  GT: 'Guatemala',
  GV: 'Guinea',
  GY: 'Guyana',
  GZ: 'Gaza Strip',
  HA: 'Haiti',
  HK: 'Hong Kong',
  HO: 'Honduras',
  HR: 'Croatia',
  HU: 'Hungary',
  IC: 'Iceland',
  ID: 'Indonesia',
  IN: 'India',
  IR: 'Iran',
  IS: 'Israel',
  IT: 'Italy',
  IV: "Côte d'Ivoire",
  IZ: 'Iraq',
  JA: 'Japan',
  JM: 'Jamaica',
  JO: 'Jordan',
  KE: 'Kenya',
  KG: 'Kyrgyzstan',
  KN: 'North Korea',
  KS: 'South Korea',
  KU: 'Kuwait',
  KV: 'Kosovo',
  KZ: 'Kazakhstan',
  LA: 'Laos',
  LE: 'Lebanon',
  LG: 'Latvia',
  LH: 'Lithuania',
  LI: 'Liberia',
  LO: 'Slovakia',
  LT: 'Lesotho',
  LU: 'Luxembourg',
  LY: 'Libya',
  MA: 'Madagascar',
  MD: 'Moldova',
  MG: 'Mongolia',
  MI: 'Malawi',
  MJ: 'Montenegro',
  MK: 'North Macedonia',
  ML: 'Mali',
  MO: 'Morocco',
  MP: 'Mauritius',
  MR: 'Mauritania',
  MT: 'Malta',
  MU: 'Oman',
  MV: 'Maldives',
  MX: 'Mexico',
  MY: 'Malaysia',
  MZ: 'Mozambique',
  NG: 'Niger',
  NI: 'Nigeria',
  NL: 'Netherlands',
  NO: 'Norway',
  NP: 'Nepal',
  NS: 'Suriname',
  NU: 'Nicaragua',
  NZ: 'New Zealand',
  OD: 'South Sudan',
  PA: 'Paraguay',
  PE: 'Peru',
  PK: 'Pakistan',
  PL: 'Poland',
  PM: 'Panama',
  PO: 'Portugal',
  PP: 'Papua New Guinea',
  QA: 'Qatar',
  RI: 'Serbia',
  RO: 'Romania',
  RP: 'Philippines',
  RS: 'Russia',
  RW: 'Rwanda',
  SA: 'Saudi Arabia',
  SE: 'Seychelles',
  SF: 'South Africa',
  SG: 'Senegal',
  SI: 'Slovenia',
  SL: 'Sierra Leone',
  SN: 'Singapore',
  SO: 'Somalia',
  SP: 'Spain',
  SU: 'Sudan',
  SW: 'Sweden',
  SY: 'Syria',
  SZ: 'Switzerland',
  TD: 'Trinidad and Tobago',
  TH: 'Thailand',
  TI: 'Tajikistan',
  TO: 'Togo',
  TS: 'Tunisia',
  TT: 'Timor-Leste',
  TU: 'Turkey',
  TW: 'Taiwan',
  TX: 'Turkmenistan',
  TZ: 'Tanzania',
  UG: 'Uganda',
  UK: 'United Kingdom',
  UP: 'Ukraine',
  US: 'United States',
  UV: 'Burkina Faso',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VE: 'Venezuela',
  VM: 'Vietnam',
  WA: 'Namibia',
  WE: 'West Bank',
  WZ: 'Eswatini',
  YM: 'Yemen',
  ZA: 'Zambia',
  ZI: 'Zimbabwe',
};

/** The country's name, or the code itself when it is not in the table. */
export function countryName(code: string): string;
export function countryName(code: string | null): string | null;
export function countryName(code: string | null): string | null {
  if (!code) return null;
  return FIPS_COUNTRY_NAMES[code] ?? code;
}
