/**
 * USGS — earthquakes of magnitude 4.5 and above in the past day.
 *
 * Why this is on a supply chain monitor: a strong earthquake near a port or a
 * semiconductor cluster is one of the few events that stops physical output
 * within hours. The page states the distance to the nearest trade node and
 * nothing more — never an impact claim.
 */

import { nearestNode } from '../nodes';
import type { Quake, Reading, UsgsData } from '../types';
import {
  LiveSourceError,
  asArray,
  fetchJson,
  isRecord,
  isoFrom,
  latestIso,
  num,
  resolveAsOf,
  str,
  type FetchedJson,
} from './http';

const MIN_MAGNITUDE = 4.5;
const URL = 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_day.geojson';

export function fetchUsgs(): Promise<FetchedJson> {
  return fetchJson(URL, 'usgs', { label: 'USGS' });
}

function parseQuake(feature: unknown): Quake | null {
  if (!isRecord(feature)) return null;
  const properties = isRecord(feature.properties) ? feature.properties : null;
  const geometry = isRecord(feature.geometry) ? feature.geometry : null;
  const coordinates = asArray(geometry?.coordinates);

  const id = str(feature.id);
  const magnitude = num(properties?.mag);
  const at = isoFrom(num(properties?.time));
  const lon = num(coordinates[0]);
  const lat = num(coordinates[1]);
  if (!id || magnitude === null || !at || lat === null || lon === null) return null;

  return {
    id,
    magnitude,
    place: str(properties?.place) ?? 'Location not given',
    at,
    url: str(properties?.url) ?? `https://earthquake.usgs.gov/earthquakes/eventpage/${id}`,
    lat,
    lon,
    depthKm: num(coordinates[2]),
    tsunamiFlag: num(properties?.tsunami) === 1,
    pagerAlert: str(properties?.alert),
    nearest: nearestNode(lat, lon),
  };
}

export function parseUsgs({ body, served }: FetchedJson): Reading<UsgsData> {
  if (!isRecord(body)) throw new LiveSourceError('USGS returned an unexpected shape.');

  const quakes = asArray(body.features)
    .map(parseQuake)
    .filter((quake): quake is Quake => quake !== null)
    .sort((a, b) => b.magnitude - a.magnitude);

  const metadata = isRecord(body.metadata) ? body.metadata : {};
  const generated = isoFrom(num(metadata.generated));
  const time = generated
    ? { asOf: generated, asOfBasis: 'feed generated by USGS', notes: [] as string[] }
    : resolveAsOf(latestIso(quakes.map((q) => q.at)), 'latest event in feed', served, 'USGS');

  return {
    status: 'ok',
    source: 'usgs',
    asOf: time.asOf,
    asOfBasis: time.asOfBasis,
    data: { minMagnitude: MIN_MAGNITUDE, windowHours: 24, quakes },
    notes: time.notes,
  };
}
